### ISSUE TITLE
Can InfluxDB IOx publish its line_protocol parser using the `influxdb_line_protocol` name?

### ISSUE THREAD

**Issue by alamb** [Hakuyume/influxdb-rs#7]
@Hakuyume 👋  -- Thank you 

Hi, I work for InfluxData and I am trying to publish the (rust) implementation of the line protocol parser we built for InfluxDB IOx (see https://github.com/influxdata/influxdb_iox/issues/7051)

However, you appear to own the crate named https://crates.io/crates/influxdb_line_protocol and this project hasn't progressed

Would it be possible to let me publish the InfluxDB IOx line_protocol parser using the `influxdb_line_protocol` name? What do you think?

Thank you for your consideration

**Comment by Hakuyume** [comment]
I am positive about releasing the crates.io's entry. I don't use the crate now and plan any updates.

Could you tell me the username on crates.io? I will add you or your team as a new owner.

**Comment by alamb** [comment]
> I am positive about releasing the crates.io's entry. I don't use the crate now and plan any updates.

> Could you tell me the username on crates.io? I will add you or your team as a new owner.

Thank you very much @Hakuyume -- we very much appreciate it 🙏 . My crates.io username is `alamb`: https://crates.io/users/alamb

**Comment by Hakuyume** [comment]
@alamb I've sent an invitation on crates.io. After you accept the invitation, I'll remove myself.

**Comment by alamb** [comment]
> @alamb I've sent an invitation on crates.io. After you accept the invitation, I'll remove myself.

Thank you @Hakuyume  -- I have done so

**Comment by Hakuyume** [comment]
Thank you. I removed myself.

**Comment by alamb** [comment]
Thank you so much @Hakuyume -- I confirm everything looks good from this end. It is very much appreciated. We plan to publish a new version soon (likely as 0.3.0 or 1.0.0).

Thanks again 🙏 

![Screenshot 2023-03-16 at 6 32 28 AM](https://user-images.githubusercontent.com/490673/225590351-4a1946c2-95ac-4080-9e37-c7f25f4f09c9.png)
